; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32-s3-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600
upload_port = COM13
monitor_port = COM13
monitor_rts = 0
monitor_dtr = 0

board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.partitions = app3M_fat9M_16MB.csv

build_flags =
  -I include
  -I src
  -I src/lvgl_port
  -I src/rgb_lcd_port
  -I src/touch
  -I src/io_extension
  -I src/i2c
  -DCORE_DEBUG_LEVEL=0
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
  -DLV_CONF_INCLUDE_SIMPLE

lib_deps =
  bblanchon/ArduinoJson@^6.21.4
  lvgl/lvgl@8.4.0